name: PHPStan

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:

  phpstan:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      
      # Use php-actions/phpstan
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: inc/
