name: PHPUnit (php-actions)

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
     # Use php-actions/phpunit - xUnit architecture for unit testing frameworks
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Zettatel-WCSMS
          XDEBUG_MODE: coverage
        with:
          # Specify extensions for coverage
          php_extensions: xdebug
          
          bootstrap: vendor/autoload.php
          
          # Specify configuration file
          configuration: phpunit.xml
          args: --coverage-text
