name: PHPUnit (php-actions)

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions:  mbstring, intl, xdebug
          ini-values:  post_max_size=256M, max_execution_time=180
          tools:       composer
  
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Zettatel-WCSMS
          XDEBUG_MODE: coverage          
          bootstrap: vendor/autoload.php
          
          # Specify configuration file
          configuration: phpunit.xml
          args: --coverage-text
